SELECT FLAVOR
FROM (SELECT FIRST_HALF.FLAVOR, SUM(JULY.TOTAL_ORDER+FIRST_HALF.TOTAL_ORDER) TOTAL_ORDER
    FROM FIRST_HALF
    JOIN (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR) JULY
    ON FIRST_HALF.SHIPMENT_ID = JULY.SHIPMENT_ID
    GROUP BY FIRST_HALF.FLAVOR
    ORDER BY TOTAL_ORDER DESC) A
LIMIT 3